<?php

function ajax_link_menu() {
    $items['ajax-test'] = array(
            'title' => 'AJAX Test',
            'type' => MENU_NORMAL_ITEM,
            'page callback' => 'ajax_link_page',
            'access arguments' => array('access content'),
    );

    $items['my-ajax-test/%'] = array(
            'title' => 'AJAX Test callback',
            'type' => MENU_CALLBACK,
            'page callback' => 'ajax_link_callback',
            'page arguments' => array(1),
            'access arguments' => array('access content'),
    );

    return $items;
}

function ajax_link_page() {
    return array(
        '#type' => 'link',
        '#title' => t('Ajax Link'),
        '#href' => 'my-ajax-test/nojs',
        '#prefix' => '<div id="ajax-link">',
        '#suffix' => '</div><div id="ajax-display"></div>',
        '#ajax' => array(
            'effect' => 'fade',
        ),
    );
}

function ajax_link_callback($ajax) {
    $time = t('The current time is : !time', array('!time' => date('Y-m-d H:i:s')));

    if ($ajax == 'ajax') {
        $commands = array();


        // AJAX command to replace the #ajax-display element with the current time.
        $commands[] = ajax_command_replace('#ajax-display', '<div id="ajax-display">' . $time . "</div>");

        // Add a visual "changed" marker to the '#ajax-display' element.
        $commands[] = ajax_command_changed('#ajax-display');

        // Trigger our ajax link jQuery plugin.
        $commands[] = ajax_command_invoke(NULL, "ajax_link");

        // Menu 'page callback' and #ajax['callback'] functions are supposed to
        // return render arrays. If returning an AJAX commands array, it must be
        // encapsulated in a render array structure.
        ajax_deliver(
            array(
                '#type' => 'ajax',
                '#commands' => $commands
            )
        );
    } else {
        // No AJAX, just display the time on a page using renderable array.
        return array(
                '#markup' => $time,
        );
    }
}
